### ISSUE TITLE
.validate() behavior

### ISSUE THREAD

**Issue by majidaldo** [pygraphkit/graphtik#2]
...should return True instead of None on success. On invalid input, i don't think it should throw a (python) error; that would be for unhandled situations.

```
class Validation:
    def ___bool___(self): ...
   @property
  def reason(self): ...
```

**Comment by ankostis** [comment]
Are you sure this comment is relevant for this project?
Any more contect?

**Comment by ankostis** [comment]
Got no reponse, assume was a mistake.
